"""init

Revision ID: f10d59e7ac1e
Revises: 
Create Date: 2024-12-29 18:21:55.967986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10d59e7ac1e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('productionYear', sa.Integer(), nullable=False),
    sa.Column('licensePlate', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licensePlate')
    )
    op.create_table('garage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car_garage',
    sa.Column('carId', sa.Integer(), nullable=False),
    sa.Column('garageId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carId'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['garageId'], ['garage.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('carId', 'garageId')
    )
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serviceType', sa.String(length=255), nullable=False),
    sa.Column('scheduledDate', sa.Date(), nullable=True),
    sa.Column('carId', sa.Integer(), nullable=True),
    sa.Column('garageId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['carId'], ['car.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garageId'], ['garage.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance')
    op.drop_table('car_garage')
    op.drop_table('garage')
    op.drop_table('car')
    # ### end Alembic commands ###
